# NUMPY :- IT IS A PACKAGE / LIBRARY FOR DEALING WITH THE NUMBERS

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(1,46,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45])

#### above is representing the array of numbers starting from "1" and ending at "46" with a stepsize of 2 and 46 value won't get into the array since it is the stop value after 45 being printed. 

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### when "np.zeros(value)" is given then only 0's will get printed but by value number of times and IN FLOAT DATATYPE...but if we want it as any other datatype the we need to write "np.zeros(value,datatype)"
#### when we want to print a 2-D array of 1's/0's then we need to write "np.zeros(row,column)" / "np.ones(row,column)" 

In [25]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.ones((3,6),int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#### when we need to typecast A 2-D array to any of the datatype(int/float) we need to write in as "np.zeros((row,column),datatype)" / "np.ones((row,column),datatype)".

#### Otherwise both the 2-D / 1-D array set its values to float by default.

In [33]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
np.linspace(3,300,10)

array([  3.,  36.,  69., 102., 135., 168., 201., 234., 267., 300.])

#### in linspace attribute we have to give a start value, end value, the number for even distribution of elements in the array (or trhe number of elements in the array).
#### for example: - np.linspace(0,1,5) means that the array will contain 5 elements and it'll get distributed as  "(1-0) / (5-1) = 0.25"
####                     : - np.linspace(0,300,3) means that the array will contain 3 elements and it'll get distributed as  "(300-0) / (3-1) = 150"    

In [40]:
np.linspace(0,300,3)

array([  0., 150., 300.])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### the above represents the identity matrix of 5x5 with the diagonal elements as "1". [that's why its written as EYE(5)]

In [132]:
np.random.rand(3,2)

array([[0.65124601, 0.85362734],
       [0.63403575, 0.03080053],
       [0.13686292, 0.33806298]])

In [173]:
np.random.randn(3,2)

array([[ 0.64405531, -0.12925027],
       [-0.45416988,  0.10906408],
       [-1.16465759, -0.95363199]])

In [194]:
np.random.randint(3,99)

31

In [230]:
np.random.randint(20,56,100)

array([29, 34, 55, 50, 24, 42, 39, 42, 29, 34, 42, 42, 39, 33, 48, 26, 28,
       23, 37, 54, 44, 25, 44, 23, 32, 41, 22, 23, 46, 33, 55, 27, 20, 48,
       32, 40, 37, 24, 32, 36, 53, 31, 37, 24, 22, 48, 45, 51, 50, 44, 41,
       26, 51, 52, 43, 49, 26, 22, 30, 20, 52, 49, 39, 36, 43, 38, 51, 31,
       55, 23, 42, 45, 30, 38, 44, 43, 40, 43, 50, 21, 46, 41, 46, 51, 27,
       21, 20, 48, 22, 25, 33, 53, 29, 44, 30, 50, 40, 49, 22, 46])

#### randn = for generating NORMAL RANDOM NUMBER.(for both +ve and -ve)
#### randint(start,end) = for generating ANY INTEGER RANDOM NUMBER.
#### randint(start,end,number of elements(LET N)) = for generating 'N' RANDOM NUMBERS BETWEEN start and end elements.

In [380]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [343]:
rand_array = np.random.randint(0,100,20)
rand_array

array([10, 34, 99, 87, 99, 14, 37,  7, 74, 90, 62, 83, 23, 82, 70, 24,  8,
       49, 21, 54])

In [381]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [344]:
rand_array.min()

7

In [345]:
rand_array.max()

99

In [346]:
rand_array.argmin()

7

In [347]:
rand_array.argmax()

2

#### here "ARG" means the argument which gives the index of the element as output when called. Here argmax() and argmin() returns the index of the maximum and the minimum value when called.
#### for example: - in the above examples " 7 " is the index of " 7 " (minimum value of rand_array) and " 2 " is the index of " 99 " (maximum value of rand_array).

In [349]:
sample_array.dtype

dtype('int32')

In [350]:
rand_array.dtype

dtype('int32')

In [358]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [359]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [366]:
a=np.random.rand(2,3)
a

array([[0.5229754 , 0.38198718, 0.56473809],
       [0.25583612, 0.23506411, 0.0019773 ]])

In [367]:
a.T

array([[0.5229754 , 0.25583612],
       [0.38198718, 0.23506411],
       [0.56473809, 0.0019773 ]])

#### " T " is the attribute used for taking out the transpose of the array.

In [392]:
sample_array = np.arange(10,22)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [393]:
sample_array.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [394]:
sample_array[7]

17

In [395]:
sample_array[-3]

19

In [396]:
sample_array[3:7]

array([13, 14, 15, 16])

In [399]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20,  21])

#### [start,end] represents the start and the end points of the array to be printed when called and even all th elements in that range can be assigned to a value (since we know that it is mutable).
#### when we print the values from start to end the value will be printed till the previous element of the end element.

In [401]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [402]:
subset_sample_array[:]= 1011
subset_sample_array

array([1011, 1011, 1011, 1011, 1011, 1011, 1011])

#### in similar fashion the subsets of the set of array can be formed and modified as per our requirement.

In [403]:
sample_array

array([1011, 1011, 1011, 1011, 1011, 1011, 1011,   17,   18,   19,   20,
         21])

## TWO DIMENSIONAL ARRAY

In [405]:
import numpy as np

In [406]:
sample_matrix = np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [407]:
sample_matrix[0][2]

1

In [408]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [409]:
sample_matrix[:,2]

array([ 1, 21, 24])

In [414]:
sample_matrix[:,3]

array([23, 33,  7])

In [415]:
sample_matrix[2]

array([56, 76, 24,  7])

In [417]:
sample_matrix[:,(3,2)]


array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [421]:
sample_matrix[(2,3)]

7

## SELECTION TECHNIQUES

In [422]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [423]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [424]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [425]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [426]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [427]:
np.max(sample_array)

19

In [428]:
np.min(sample_array)

1

In [429]:
np.argmin(sample_array)

0

In [430]:
np.argmax(sample_array)

18

In [431]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [432]:
np.std(sample_array)

5.477225575051661

In [433]:
np.mean(sample_array)

10.0

In [434]:
np.var(sample_array)

30.0

In [440]:
array = np.random.randn(3,4)
array

array([[-0.25152088,  1.3358387 , -1.11322198, -0.40922652],
       [ 0.52173829, -0.5207966 ,  2.36632757,  0.98827036],
       [ 0.2133107 , -0.94730319, -2.18844293, -0.40323102]])

In [442]:
np.round(array,decimals=3)

array([[-0.252,  1.336, -1.113, -0.409],
       [ 0.522, -0.521,  2.366,  0.988],
       [ 0.213, -0.947, -2.188, -0.403]])

In [454]:
sports=np.array(["golf","cricket","football","hockey","football"])
np.unique(sports)

array(['cricket', 'football', 'golf', 'hockey'], dtype='<U8')